//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant_manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula
    {
        public int Id { get; set; }
        public int DishesId { get; set; }
        public int ProductId { get; set; }
        public double Count { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Product Product { get; set; }
    }
}
