//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant_manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Product_category> Product_categorySet { get; set; }
        public virtual DbSet<Dishes> DishesSet { get; set; }
        public virtual DbSet<Guests> GuestsSet { get; set; }
        public virtual DbSet<Reservation> ReservationSet { get; set; }
        public virtual DbSet<Staff_Pos> Staff_PosSet { get; set; }
        public virtual DbSet<Staff> StaffSet { get; set; }
        public virtual DbSet<Ready_Dishes> Ready_DishesSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Dishes_categories> Dishes_categoriesSet { get; set; }
        public virtual DbSet<Formula> FormulaSet { get; set; }
        public virtual DbSet<Tables> TablesSet { get; set; }
        public virtual DbSet<Check> CheckSet { get; set; }
    }
}
