//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant_manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables
    {
        public int Id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Order_Dishes Order_Dishes { get; set; }
        public virtual Сheck Сheck { get; set; }
    }
}
